name: admin CI/DC Docker Sample

on:
  push:
    branches: [main]
env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/styleseller-admin
  VERSION: ${{ github.sha }}
  NAME: admin_sample
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
        with:
          node-version: lts/Hydrogen

      - name: Cache node modules
        uses: actions/cache@v2.1.8
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: build-prd

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.prd
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/admin
